services:

    # Controllers

    marvel.home.controller:
        class: Sihades\Marvel\CatalogBundle\Controller\HomeController

    marvel.characters.controller:
        class: Sihades\Marvel\CatalogBundle\Controller\CharactersController
        calls:
            - [ setRequest, ['@marvel.characters.request']]

    # Requests

    marvel.abstract.request:
        class: Sihades\Marvel\CatalogBundle\Request\AbstractRequest

    marvel.characters.request:
        class: Sihades\Marvel\CatalogBundle\Request\CharactersRequest
        calls:
           - [ setPrivateKey, ['%marvel.private_key%']]
           - [ setPublicKey, ['%marvel.public_key%']]
           - [ setHandler, ['@marvel.cache_request.handler']]
           - [ setEndpoint, ['%marvel.endpoints.characters%']]

    # Handler

    marvel.cache_request.handler:
        class: Sihades\Marvel\CatalogBundle\Handler\CacheRequestHandler
        arguments: ['%marvel.base_url%', '%marvel.cache_dir%']
