services:

    # Controllers

    marvel.home.controller:
        class: Sihades\Marvel\CatalogBundle\Controller\HomeController

    marvel.characters.controller:
        class: Sihades\Marvel\CatalogBundle\Controller\CharactersController
        calls:
            - [ setMarvelRequest, ['@marvel.request']]
            - [ setEndpoint, ['%marvel.endpoints.characters%']]
            - [ setPaginatorLimit, ['%paginator.limit%']]

    # Requests

    marvel.request:
        class: Sihades\Marvel\CatalogBundle\Request\MarvelRequest
        calls:
            - [ setPrivateKey, ['%marvel.private_key%']]
            - [ setPublicKey, ['%marvel.public_key%']]
            - [ setHandler, ['@marvel.cache_request.handler']]

    # Handler

    marvel.cache_request.handler:
        class: Sihades\Marvel\CatalogBundle\Handler\CacheRequestHandler
        arguments: ['%marvel.base_url%', '%marvel.cache_dir%']
